Update cicd.yaml

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -21,20 +21,20 @@ jobs:
     - name: Setup .NET Core 8.0
       uses: actions/setup-dotnet@v3
       with:
-        dotnet-version: 8.0.x
+        dotnet-version: 8.0.100
 
     # Restore dependencies
     - name: Restore dependencies
-      run: dotnet restore
+      run: dotnet restore SneakerSZN/SneakerSZN.sln
 
     # Run tests (continue on error)
     - name: Run Tests
       run: |
-        dotnet test --no-restore || echo "Tests failed but continuing..."
+        dotnet test SneakerSZN/SneakerSZN.sln --no-restore || echo "Tests failed but continuing..."
 
     # Build the project
     - name: Build the project
-      run: dotnet build --no-restore --configuration Release
+      run: dotnet build SneakerSZN/SneakerSZN.sln --no-restore --configuration Release
 
     # Log in to Docker Hub
     - name: Log in to Docker Hub
@@ -46,5 +46,5 @@ jobs:
     # Build and push Docker image
     - name: Build and Push Docker Image
       run: |
-        docker build -t deanmiciels/sneakerbackend:latest .
+        docker build -t deanmiciels/sneakerbackend:latest SneakerSZN
         docker push deanmiciels/sneakerbackend:latest
